<?php
#############################################################################
# Language depended translations of diverse messages and labels used        #
# overall in this plugin.                                                   #
#                                                                           #
# Author: consros 2008                                                      #
#############################################################################

define("LANG_NOT_IMPLEMENTED", "<br /><b>Опция временно не работает!</b>");
define("LANG_SAVE_CHANGES", "Сохранить изменения");

define("LANG_YES", "Да");
define("LANG_NO",  "Нет");

define("LANG_USERNAME", "Имя пользователя");
define("LANG_USERNAME_DETAILS", "Введите номер аккаунта, полученный от Kartina.TV");

define("LANG_PASSWORD", "Пароль пользователя");
define("LANG_PASSWORD_DETAILS", "Введите пароль аккаунта, полученный от Kartina.TV");

define("LANG_ADULT", "Каналы для взрослых");
define("LANG_ADULT_DETAILS", "Разрешить или нет доступ к эротическим каналам");

define("LANG_TIME_ZONE", "Часовой пояс");
define("LANG_TIME_ZONE_DETAILS", "Для корректного отображения времени в программах телепередач рекомендуется установить локальную временную зону");

define("LANG_BUFFER_SIZE", "Буфферизация видеопотока");
define("LANG_BUFFER_SIZE_DETAILS", "Если у Вас нестабильное интернет-соединение, заметны прерывания и/или ускорения вещания, эта настройка может помочь. (Mb)");

?>
