<?php
#############################################################################
# Kartina.tv authorization data.                                            #
# Put here your account settings which you have got from kartina.tv         #
#                                                                           #
# You can also use one of test accounts with limited functionality:         #
#   USERNAME: 140; PASSWORD: 041                                            #
#   USERNAME: 141; PASSWORD: 141                                            #
#   USERNAME: 142; PASSWORD: 241                                            #
#   USERNAME: 143; PASSWORD: 341                                            #
#   USERNAME: 144; PASSWORD: 441                                            #
#   USERNAME: 145; PASSWORD: 541                                            #
#   USERNAME: 146; PASSWORD: 641                                            #
#   USERNAME: 147; PASSWORD: 741                                            #
#   USERNAME: 148; PASSWORD: 841                                            #
#   USERNAME: 149; PASSWORD: 941                                            #
#                                                                           #
# Author: consros 2008                                                      #
#############################################################################

$USERNAME=148;
$PASSWORD=841;
$ALLOW_EROTIC=TRUE;
?>
