<?php
#############################################################################
# Language depended translations of diverse messages and labels used        #
# overall in this plugin.                                                   #
#                                                                           #
# Author: consros 2010                                                      #
#############################################################################

define("LANG_YES", "Да");
define("LANG_NO",  "Нет");

define("LANG_EPG_FROM", "за");
define("LANG_EPG_PAGE", "страница");

define("LANG_WEEK_DAYS", "Вс,Пн,Вт,Ср,Чт,Пт,Сб");

define("LANG_DAYS_LIST", "Переход к нужному дню");
define("LANG_CHANNELS_LIST", "Список каналов");

define("LANG_NOT_IMPLEMENTED", "<br /><b>Опция временно не работает!</b>");
define("LANG_SAVE_CHANGES", "Сохранить изменения");

define("LANG_USERNAME",         "Имя пользователя");
define("LANG_USERNAME_DETAILS", "Введите номер аккаунта, полученный от Kartina.TV");

define("LANG_PASSWORD",         "Пароль пользователя");
define("LANG_PASSWORD_DETAILS", "Введите пароль аккаунта, полученный от Kartina.TV");

define("LANG_ADULT",         "Каналы для взрослых");
define("LANG_ADULT_DETAILS", "Разрешить или нет доступ к эротическим каналам");

define("LANG_TIME_ZONE",         "Часовой пояс");
define("LANG_TIME_ZONE_DETAILS", "Для корректного отображения времени в программах телепередач рекомендуется установить локальную временную зону");

define("LANG_BUFFER_SIZE",         "Буфферизация видеопотока");
define("LANG_BUFFER_SIZE_DETAILS", "Если у Вас нестабильное интернет-соединение, заметны прерывания и/или ускорения вещания, эта настройка может помочь. (Mb)");

define("LANG_SORTING",         "Пользовательская сортировка каналов");
define("LANG_SORTING_DETAILS", "Разрешить пользовательскую сортировку каналов с помощью файла правил <b>sorting.txt</b>");


define("LANG_ERR_AUTHORIZATION",     "Пользователю отказано в доступе");
define("LANG_ERR_SESSION_TIMEOUT",   "Сессия пользователя завершена, попробуйте позднее");
define("LANG_ERR_SERVER_CONNECTION", "Нет соединения с сервером");
define("LANG_ERR_SERVER_RESPONSE",   "Сервер не отвечает, либо формат ответа не поддерживается. Отмена");

define("LANG_ERR_URL_READ",          "Адрес недоступен");
define("LANG_ERR_FILE_READ",         "Ошибка при чтении файла");
define("LANG_ERR_FILE_WRITE",        "Ошибка при записи файла");

define("LANG_ERR_CHANNEL_OPEN",      "Канал закрыт или временно недоступен");
define("LANG_ERR_NO_EPG",            "Программа передач недоступна");

?>
